--- 
#Frontend Role 
- name: Clone Repository 
  git: 
    repo: 'https://github.com/whitearodi/yolo2.git'
    dest: /var/www/client
  notify:
    - Restart client container

- name: Build & start client container 
  docker_container:
     name: react_app
     image: "{{client_image}}"
     state: started
     restart_policy: always 
     ports: 
       - "3001:3001"
     volumes: 
        - /var/www/client:/var/www/client
     networks_cli_compatible: yes
     networks: 
        - name: yolo_net 

