apiVersion: v1
kind: Service
metadata:
  name: server-backend-service 
  namespace: yolo-namespace
spec:
  type: LoadBalancer
  selector:
    app: server_backend
  ports:
  - port: 80
    targetPort: 5000
