version: "3.5"

services:
  client:
    build:
      context: ./client 
      dockerfile: Dockerfile
    container_name: react_app
    command: "npm start"
    ports:
      - "3001:3001"
    volumes:
      - "./client:/var/www/client"
    networks:
      - yolo_net 
    image: arodi21/client_side:v1.1.1 #Tag the client image 
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server_backend
    command: "npm start"
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/var/www/backend"
    networks:
     - "yolo_net"
    image: arodi21/server_backend:v1.1.1 #Tag the backend image 
  
  yolo.db:
    image: mongo:latest
    container_name: yolo_db
    environment:
     MONGO_INITDB_ROOT_USERNAME: admin
     MONGO_INITDB_ROOT_PASSWORD: password 
     MONGO_INITDB_DATABASE: local 
    ports:
      - "0.0.0.0:27018:27017"
    networks:
      - yolo_net

networks:
  yolo_net:
    driver: bridge
      

