apiVersion: v1
kind: Service
metadata:
  name: yolo-db-service
  namespace: yolo
spec:
  selector:
    app: yolo_db
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  type: ClusterIP
