---
# Backend Role
#Cloning repo  
- name: Clone Repository
  git:
    repo: "https://github.com/whitearodi/yolo2.git"
    dest: "/var/www/backend"
  notify:
    - Restart backend container

#Configuring the containers 
- name: Build & start backend container 
  docker_container:
     name: server_backend 
     image: "{{ backend_image }}"
     state: started 
     restart_policy: always 
     ports: 
       - "5000:5000"
     volumes: 
       - /var/www/backend:/var/www/backend
     networks_cli_compatible: yes
     networks:
        - name: yolo_net
     env:
      MONGODB_URL: "mongodb://yolo_db:27018"
      DB_NAME: yolo_db